pipeline {
    agent any
    environment {
        BUILD_DIR = 'build'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Configure') {
            steps {
                sh '''
                mkdir -p ${BUILD_DIR}
                cd ${BUILD_DIR}
                cmake -DCMAKE_BUILD_TYPE=Release ..
                '''
            }
        }
        stage('Build') {
            steps {
                sh '''
                cd ${BUILD_DIR}
                make -j$(sysctl -n hw.ncpu)
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                cd ${BUILD_DIR}
                ./runTests --gtest_output=xml:test_report.xml
                '''
            }
            post {
                always {
                    junit "${BUILD_DIR}/test_report.xml"
                }
            }
        }
    }
}
